import React from 'react';

import type { Metadata } from 'next';
import GlobalStyle from '@/ui/layouts/GlobalStyle';
import StyledComponentsRegistry from '@/lib/registry';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <StyledComponentsRegistry>
               <GlobalStyle />
               {children}
            </StyledComponentsRegistry>
         </body>
      </html>
   );
}
